FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=development
ENV NEXT_PUBLIC_API_URL=http://api:8080
ENV WATCHPACK_POLLING=true

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
